import type { Expectations } from "./types";

export const expectations: Expectations = {
  companyId: 1,
  ticker: "BIMBOA",
  quarter: "1Q26",
  sourceFile:
    "/Users/anibalin/Sites/2026/marcelo/public/camila/ReporteTrimestral_BIMBO_1Q26.pdf",
  minExtractedValues: 35,

  projPreApprovalCells: {
    "PROJ:r5":  { value: 100318.746, label: "Ingresos" },
    "PROJ:r7":  { value: -47662.443, label: "Costo de ventas" },
    "PROJ:r9":  { value: 52656.303, label: "Utilidad bruta" },
    "PROJ:r11": { value: -36980.520, label: "Gastos de venta" },
    "PROJ:r13": { value: 7911.417, label: "Utilidad (pérdida) de operación" },
    "PROJ:r15": { value: 118.381, label: "Ingresos financieros" },
    "PROJ:r16": { value: -3580.047, label: "Gastos financieros" },
    "PROJ:r29": { value: -6.919, label: "Participación en la utilidad (pérdida) de asociadas y negocios conjuntos" },
    "PROJ:r30": { value: 4442.832, label: "Utilidad (pérdida) antes de impuestos" },
    "PROJ:r31": { value: -1643.848, label: "Impuestos a la utilidad" },
    "PROJ:r33": { value: -437.037, label: "Utilidad (pérdida) atribuible a la participación no controladora" },
    "PROJ:r35": { value: 2798.984, label: "Utilidad (pérdida) neta" },
    "PROJ:r42": { value: 19573.957, label: "Efectivo y equivalentes de efectivo" },
    "PROJ:r45": { value: 75607.676, label: "Total de activos circulantes" },
    "PROJ:r55": { value: 418882.803, label: "Total de activos" },
    "PROJ:r60": { value: 84830.508, label: "Total de pasivos circulantes" },
    "PROJ:r63": { value: 27988.344, label: "Clientes y otras cuentas por cobrar" },
    "PROJ:r64": { value: 16887.253, label: "Inventarios" },
    "PROJ:r69": { value: 156615.057, label: "Propiedades, planta y equipo" },
    "PROJ:r70": { value: 295396.164, label: "Total pasivos" },
    "PROJ:r76": { value: 72679.724, label: "Crédito mercantil" },
    "PROJ:r80": { value: 123486.639, label: "Total de capital contable" },
    "PROJ:r82": { value: 6335.237, label: "Otros pasivos financieros a corto plazo" },
    "PROJ:r83": { value: 37899.545, label: "Proveedores y otras cuentas por pagar a corto plazo" },
    "PROJ:r88": { value: 154130.696, label: "Otros pasivos financieros a largo plazo" },
    "PROJ:r90": { value: 8248.453, label: "Pasivo por impuestos diferidos" },
    "FAT:r23":  { value: 39726, label: "Ventas Netas|México" },
    "FAT:r27":  { value: 21952, label: "Utilidad Bruta|México" },
    "FAT:r33":  { value: 6044, label: "Utilidad de Operación|México" },
    "FAT:r38":  { value: 8159, label: "UAFIDA Ajustada|México" },
    "FAT:r49":  { value: 40533, label: "Ventas Netas|Norteamérica" },
    "FAT:r53":  { value: 21997, label: "Utilidad Bruta|Norteamérica" },
    "FAT:r59":  { value: 1178, label: "Utilidad de Operación|Norteamérica" },
    "FAT:r64":  { value: 3468, label: "UAFIDA Ajustada|Norteamérica" },
    "FAT:r77":  { value: 12631, label: "Ventas Netas|EAA" },
    "FAT:r81":  { value: 4390, label: "Utilidad Bruta|EAA" },
    "FAT:r87":  { value: 330, label: "Utilidad de Operación|EAA" },
    "FAT:r92":  { value: 1116, label: "UAFIDA Ajustada|EAA" },
    "FAT:r105": { value: 11545, label: "Ventas Netas|Latinoamérica" },
    "FAT:r108": { value: 4945, label: "Utilidad Bruta|Latinoamérica" },
    "FAT:r114": { value: 228, label: "Utilidad de Operación|Latinoamérica" },
    "FAT:r119": { value: 1057, label: "UAFIDA Ajustada|Latinoamérica" },
  },

  fatSheet: "FAT",
  fatAfterRecalc: {
    AT23: { value: 39726, label: "Ventas Netas|México" },
    AT27: { value: 21952, label: "Utilidad Bruta|México" },
    AT33: { value: 6044, label: "Utilidad de Operación|México" },
    AT38: { value: 8159, label: "UAFIDA Ajustada|México" },
    AT49: { value: 40533, label: "Ventas Netas|Norteamérica" },
    AT53: { value: 21997, label: "Utilidad Bruta|Norteamérica" },
    AT59: { value: 1178, label: "Utilidad de Operación|Norteamérica" },
    AT64: { value: 3468, label: "UAFIDA Ajustada|Norteamérica" },
    AT77: { value: 12631, label: "Ventas Netas|EAA" },
    AT81: { value: 4390, label: "Utilidad Bruta|EAA" },
    AT87: { value: 330, label: "Utilidad de Operación|EAA" },
    AT92: { value: 1116, label: "UAFIDA Ajustada|EAA" },
    AT105: { value: 11545, label: "Ventas Netas|Latinoamérica" },
    AT108: { value: 4945, label: "Utilidad Bruta|Latinoamérica" },
    AT114: { value: 228, label: "Utilidad de Operación|Latinoamérica" },
    AT119: { value: 1057, label: "UAFIDA Ajustada|Latinoamérica" },
  },

  projDuplicatePairs: [],

  acceptedValidationWarnings: [
    /DeepSeek source judge.*[Ee]vidence snippet does not/,
    /DeepSeek source judge.*[Ii]nsufficient evidence/,
    /DeepSeek source judge.*[Cc]annot verify/,
  ],
};
